### ISSUE TITLE
Remove or make it grey characters Q X V from polish keyboard

### ISSUE THREAD

**Issue by paspyy** [Deykun/diffle-lang#57]
If there are no polish characters in the word, we are making them unavailable on the keyboard. The same we could do with Q X V, since polish words does not conain them. Unless there are some which are accepted by dictionary but I tried 'quiz' or 'taxi' and they are not allowed. If this is the case, we can make them unavailable for selection.

**Comment by Deykun** [comment]
Hi there! There are **279** words with "x" (e.g., beatbox, cybersex, sebixowi ;D) that are accepted, **222** with "v" (e.g., Casanova, pendrive, rave), and **one** with "q" (boutique).

I also considered these letters and I'm blocking words with them as winning words because they are often foreign. I briefly considered removing them from the keyboard completely or providing an option to hide them for the Polish language. However, I decided against it because players may use those letters, and more importantly, everyone expects to see QWERTY in they keyboard.

I understand your point, and I tend to overanalyze the game as well. However, most people don't think about these letters when they enter the site and if I were to mark those letters differently, it may have the opposite effect of what we want. For Polish characters it's a useful tip to underline them and emphasize that they aren't part of the word. I think it's okay to leave qxv as part of the mystery.

Using Polish characters in a game with them is penalized with the red dot 🔴. If I were to mark x, v, q I would need to penalize them as well.

**Comment by paspyy** [comment]
Alright, if there are words allowed, then let them stay. It will be funny if one of those words will be selected, it will be quite a challenge. But Im still suprised that obvious foreign words ones are not allowed.

**Comment by paspyy** [comment]
Ok, instead of taxi there is taksówka and guess what, instead of quiz there is kwiz. Omg

**Comment by Deykun** [comment]
I'm using the sjp.pl dictionary, used and maintained by kurnik.pl. I suspect that they avoid this problem by not giving tiles with those letters in Literalki (Scrabble).
